### ISSUE TITLE
hicodec

### ISSUE THREAD

**Issue by f1vefour** [OtherCrashOverride/c2enc#1]
What is hicodec if you don't mind?

*edit*
This was meant for a clone repo, sorry crash.

**Comment by leandrotsampa** [comment]
> 
> 
> What is hicodec if you don't mind?
> 
> _edit_
> This was meant for a clone repo, sorry crash.

hicodec is a alternative to vpcodec in hisilicon board.

**Comment by f1vefour** [comment]
Thank you.
